[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "f1tenth_gym"
version = "1.0.0dev"
description = "Gym environment for F1TENTH"
readme = "README.md"
requires-python = ">=3.10, <3.12"

dependencies = [
    "gymnasium>=0.28.1",
    "moviepy>=1.0.3",
    "numpy>=2.2.5",
    "pillow>=9.0.1",
    "scipy>=1.7.3",
    "numba>=0.55.2",
    "PyYAML>=5.3.1",
    "pygame>=2.5.2",
    "opencv-python>=4.9.0.80",
    "yamldataclassconfig>=1.5.0",
    "requests>=2.31.0",
    "shapely>=2.0.2",
    "matplotlib>=3.8.3",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.4",
    "black>=23.12.1",
    "ipykernel>=6.29.0",
    "isort>=5.13.2",
    "autoflake>=2.2.1",
    "matplotlib>=3.8.2", # Note: matplotlib is also in core dependencies, this might be intentional or a duplicate
    "flake8>=7.0.0",
]

[tool.setuptools]
packages = {find = {}}